name: Automatically assign me to new issues
on:
  issues:
    types: [opened]
jobs:
  assign-me:
    runs-on: ubuntu-latest
    steps:
    - name: Assign me
      run: |
        issue_number=${{ github.event.issue.number }}
        response=$(gh api repos/${{ github.repository }}/issues/$issue_number/assignees -f assignees='["Reenuay"]' -X POST)
        echo "API response: $response"
      env:
        GH_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
