name: Automatically assign me to new issues
on:
  issues:
    types: [opened]
jobs:
  assign-me:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Assign me
      run: |
        issue_number=${{ github.event.issue.number }}
        gh issue edit $issue_number --add-assignee "Reenuay"
      env:
        GH_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
